### ISSUE TITLE
IST Mobilfunkvorwahl (zB 0179) für einen Antragsteller wird verschluckt

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgang-anlegen-api#1]

**Comment by timFriedmann** [comment]
Übergibt man für das Feld Vorwahl zur Telefonnummer eines Antragstellers eine Mobilfunkvorwahl (z.B. 0179) wird diese nicht in Europace2 ausgegeben. Standardvorwahlen wie 030 funktionieren aber.

**Comment by gruenewa** [comment]
@timFriedmann @caspii  Ich kann den Fehler leider nicht nachstellen. Ein Test mit ...

      <telefonnummer>65487213</telefonnummer>
      <telefonnummerVorwahl>0179</telefonnummerVorwahl>

im Antragsteller funktioniert bei mir. Könntet ihr das eventuell nochmal prüfen? Könnt ihr den Fehler irgendwie reproduzieren? Eventuell könntet ihr eine exemplarische Soap-Message liefern, welche den Fehler demonstriert.

**Comment by timFriedmann** [comment]
Sorry, 
war Fehlalarm unsererseits. Ticket kann geschlossen werden.
