### ISSUE TITLE
ChangeLog BEX X->Y

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-vorgang-anlegen-api#18]
Wäre es evtl. möglich ein kurzes ChangeLog einzustellen, damit man sehen kann was genau sich zwischen den Versionen geändert hat?

**Comment by unstko** [comment]
Anstatt mit Changelogs arbeiten wir bei unseren APIs mit Releases. Ich habe daher ein Release für Version 14 erzeugt und die darin enthaltenen Änderungen aufgelistet:
https://github.com/europace/baufismart-vorgang-anlegen-api/releases/tag/14
