### ISSUE TITLE
Hinweis, dass die BEX API neu entwickelt wird

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgang-anlegen-api#21]
Es sollte ein Hinweis in der README geben, dass diese API bald ersetzt wird -- damit sie jetzt keiner unwissend anbindet.

cc @KoneFuzius

**Comment by SaschaKistner** [comment]
Hallo @caspii ,

Danke für den Hinweis - gibt es schon einen zeitliche Planung oder was bedeutet "bald" :)

**Comment by acodingsquirrel** [comment]
Die Doku ist angepasst. Jetzt findet man einen Hinweis, das die API ausgebaut wird.
Wir streben eine Umsetzung in Q3 2020 an.
