### ISSUE TITLE
Kosten + Grunderwerbssteuer/Notar/Makler -> Prozentübergabe?

### ISSUE THREAD

**Issue by tomuench** [europace/baufismart-vorgang-anlegen-api#3]
Guten Tag liebes Team,

mir fehlt in der Schnittstelle die Möglichkeit die Prozente für die

- Grunderwerbssteuer
- Notargebühren
- Maklergebühren

zu übergeben. Wo finde ich die oder sollten diese automatisch ermittelt werden?
![image](https://user-images.githubusercontent.com/4034506/49013959-ca7a8300-f17e-11e8-8f4c-f671067ead56.png)

Viele Grüße

**Comment by caspii** [comment]
Hi Tobias,

im Frontend machen wir in diesem Fall eine kleine Hilfsrechnung, bei der API musst Du die Beträge selber ausrechnen.

VG Caspar

**Comment by tomuench** [comment]
Hi @caspii 
mir geht es nicht um den Euro-Betrag. Sondern um die Gewerbesteuer in Prozent. Gibt es eine Möglichkeit diese mit zu übergeben?

**Comment by caspii** [comment]
@tomuench Du meinst vermutlich Grunderwerbssteuer und nicht Gewerbesteuer? 

Wenn Du den Kaufpreis kennst und die Grundsteuer in Prozent auch, dann kannst Du doch den EUR Betrag ausrechnen und übergeben, oder?

**Comment by tomuench** [comment]
Sorry beim Naming vertan. Ich meinte Grunderwerbssteuer.
Genau ich kann die Euro-Betrag übergeben, was ich jetzt auch schon mache. Kommt auch alles wie erwartet im Europace an. Jedoch werden bei der Übergabe der Schnittstelle die Prozentangabe nicht übergeben, d.h.

Grunderwerbssteuersatz von 6,5 % und einen Euro-Betrag  6760,00 €. Mir geht es hier um den Steuersatz von 6,5%.

**Comment by caspii** [comment]
OK, verstehe. Darf ich fragen, warum Dir das wichtig ist? Der Steuersatz ist meines Wissens nicht relevant für die Angebotsermittlung

**Comment by tomuench** [comment]
Frage kam durch einen Benutzer meiner Software auf. Er wollte gerne auch den Steuersatz übertragen haben, damit die Daten möglichst identisch sind. Ich wollte daraufhin die Möglichkeit prüfen und deswegen bin ich hier. ;-)

**Comment by caspii** [comment]
Alles klar, verstanden.

Also die offizielle Antwort lautet: geht leider nicht
