### ISSUE TITLE
Erweiterung: SteuerID für Antragsteller

### ISSUE THREAD

**Issue by tomuench** [europace/baufismart-vorgang-anlegen-api#4]
Moin Liebes Team,

ist es geplant oder besteht die Möglichkeit die SteuerIDs für die Antragsteller mit zu übergeben?

Viele Grüße

**Comment by caspii** [comment]
Es ist geplant. Wann es kommt ist momentan unbekannt.

**Comment by caspii** [comment]
Erledigt
