### ISSUE TITLE
Zwei Antragsteller - nicht verheiratet

### ISSUE THREAD

**Issue by tomuench** [europace/baufismart-vorgang-anlegen-api#6]
Hallo Liebes Team,

wir haben gerade folgende Fragestellung erhalten:

Wie können zwei Antragsteller (beide verheiratet, aber nicht miteinander) im Europace abgebildet werden? Sowohl die UI als auch die Schnittstelle deuten eher daraufhin, das solche Fälle er Randbereiche sind.

Gibt es für diese Fälle eine Art Best Practice? Vermögen einfach summieren für beide Antragsteller? Gibt es einen Flag, der zeigt, dass die Antragsteller nicht miteinander verheiratet sind?

Viele Grüße und danke für euer Feedback

**Comment by Creice** [comment]
Hallo tomuench,

einen Vorgang indem beide Antragsteller verheiratet sind ABER nicht miteinander, muss man dennoch in EINEM Haushalt einstellen. Warum? Die Haushaltsrechnung der Banken würde sich sonst nachteilig auf die Antragsteller auswirken (da bei zwei Haushalten auch mit anderen Pauschalen gerechnet würde). In so einem Fall ist die Best Practice der Bank im Annahmedialog die Mitteilung mitzugeben, dass die Antragsteller nicht miteinander verheiratet sind. Für die Bank macht das m.E. auch keinen großen Unterschied, da beide Antragsteller den Kreditvertrag unterschreiben und Unterhaltszahlungen ggf. bei den Antragstellern eingetragen werden.
